Remove readStream.destroy() call on timeout
It's causing a lot of errors on closing the fd, even after
I started checking the fd before destroying it. I suppose it's the
underlying stream implementation trying to destroy() a stream twice.

net:231
  close(fd);
  ^
Error: EBADF, Bad file descriptor
    at closeFD (net:231:3)
    at Stream.destroy (net:999:17)
    at Stream.<anonymous> (http:731:12)
    at Stream.emit (events:42:20)
    at Timer.callback (net:151:19)
    at node.js:221:9

Will have to look at the Stream source code to see if I can find the
problem. Till then, the file descriptors are automatically closed when
the readStream reaches the end, so antinode shouldn't leak file
descriptors.